apiVersion: v1
kind: ServiceAccount
metadata:
  name: portal-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::027053845110:role/dev-portal-pod-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-service-portal
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: self-service-portal
  template:
    metadata:
      labels:
        app: self-service-portal
    spec:
      serviceAccountName: portal-sa
      containers:
      - name: portal
        # Replace with your actual ECR image URI once built
        image: your-account.dkr.ecr.eu-central-1.amazonaws.com/self-service-portal:v1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "dev-proxy.proxy-cduom6060vpm.eu-central-1.rds.amazonaws.com"
        - name: DB_PORT
          value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: portal-service
  namespace: default
spec:
  selector:
    app: self-service-portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP # Keeps traffic internal, we will use an Ingress to expose it